language: node_js
node_js:
  - '4'

addons:
  firefox: 'latest'

sudo: false

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - openssl aes-256-cbc -K $encrypted_1a5822ef9bcb_key -iv $encrypted_1a5822ef9bcb_iv -in deploy_key.pem.enc -out deploy_key.pem -d

install:
  - npm install

before_script:
  - npm run test:once

script:
  - npm run build

notifications:
  email:
    recipients:
      - E1ODIN_Technology@EF.com
    on_success: change
    on_failure: always

env:
  global:
    - GIT_NAME: E1 BSD
    - GIT_EMAIL: E1BSD_Technology@EF.com
