language: node_js
node_js:
  - '4'

addons:
  firefox: 'latest'

sudo: false

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

install:
  - npm install

script:
  - npm run test:once

before_deploy:
  - npm version dev.$TRAVIS_BUILD_NUMBER

deploy:
  - provider: npm
    email: $GIT_EMAIL
    api_key: $NPM_TOKEN
    skip_cleanup: true

notifications:
  email:
    recipients:
      - E1ODIN_Technology@EF.com
    on_success: change
    on_failure: always

env:
  global:
    - GIT_NAME: E1 BSD
    - GIT_EMAIL: E1BSD_Technology@EF.com
    - secure: "nnt/xlSms5Kncht5R6iGi78ljDwJBK2EHsfiwIxIiubK2Sdl1DoreZXO4V3wS6biMkIXaw5tYUEhlCiQQRoNBWOIR8396O8T2/9HSuxq9wz9OCXqd5w+XJwCGPELWxjNHnZrtNFZ7CumsBx3UP5+voLbXpPxp0i7zCKHbQ1CdGNhC/nbS3EipoJOXxXXH03lYrBw87DgrDcFgjHU+BqF+7mwlxyoAoHsflzrlz8jlUExcZNOAjX/znlzeoyYIUe/LSzmppEGyIGfVck5RCAOxbZ61vUaivu6NSWGt8xU8RAauqUH+9maXVQiJsOWUkS7Uz9QwcxLOawZfPyzV3FkyZQyoS1uAs9DCBKrvFUfX+3TUlIFtGRUK34Bm+oGIJvq0Rc8WAiRhU6qLn0bb3P7VKrwWXCT/eb6Pw4apPk4mac1TVMUAAm9rm9HjmU/8Z1Zbg7n2cXC5tO54VNnK3zpVy4L75oMQlcKs/mISfAs7Pt4vizFawLrPtv5NBEzz6dz/u7OqE0T70Lq7wP5AL7fn0xKK5JySIrQ7nTr1OPzZ2rFnIuDaKB3cAK40ZjXmFls5DC2zW/9hRmHKdjpbNXfgkLd80dkNFiEgNOqoKTKVJwxcmJzkG6ascs3zHhxz2fzHmmWgYBfhzcjUrFxb+IR48aGGv48ho3OLsdPekXknXM="
